// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "goa.learn": Application User Types
//
// Command:
// $ goagen
// --design=github.com/uzimith/goa-learn/design
// --out=$(GOPATH)/src/github.com/uzimith/goa-learn
// --version=v1.3.0

package client
