consumes:
- application/json
definitions:
  Article:
    description: Article (default view)
    example:
      created_at: 2016-03-20T09:39:48Z
      created_by: 1
      id: 1
      text: Voluptatem ea.
    properties:
      created_at:
        description: 作成日時
        example: 2016-03-20T09:39:48Z
        format: date-time
        type: string
      created_by:
        description: 作成者
        example: 1
        format: int64
        type: integer
      id:
        description: ID
        example: 1
        format: int64
        type: integer
      text:
        description: text
        example: Voluptatem ea.
        type: string
    required:
    - id
    - text
    - created_at
    title: 'Mediatype identifier: application/vnd.article+json; view=default'
    type: object
  ArticleCollection:
    description: ArticleCollection is the media type for an array of Article (default
      view)
    example:
    - created_at: 2016-03-20T09:39:48Z
      created_by: 1
      id: 1
      text: Voluptatem ea.
    - created_at: 2016-03-20T09:39:48Z
      created_by: 1
      id: 1
      text: Voluptatem ea.
    - created_at: 2016-03-20T09:39:48Z
      created_by: 1
      id: 1
      text: Voluptatem ea.
    items:
      $ref: '#/definitions/Article'
    title: 'Mediatype identifier: application/vnd.article+json; type=collection; view=default'
    type: array
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:8080
info:
  description: learning goa
  title: goa learn
  version: ""
paths:
  /article:
    get:
      description: List
      operationId: article#list
      parameters:
      - description: Filter by ids
        in: query
        items:
          type: integer
        name: id
        required: false
        type: array
      produces:
      - application/vnd.goa.error
      - application/vnd.article+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ArticleCollection'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: list article
      tags:
      - article
  /article/{id}:
    get:
      description: Get arcitle by id
      operationId: article#show
      parameters:
      - description: id
        in: path
        minimum: 1
        name: id
        required: true
        type: integer
      produces:
      - application/vnd.goa.error
      - application/vnd.article+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Article'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show article
      tags:
      - article
produces:
- application/json
responses:
  NotFound:
    description: Not Found
schemes:
- http
swagger: "2.0"
