// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "goa.learn": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/uzimith/goa-learn/design
// --out=$(GOPATH)/src/github.com/uzimith/goa-learn
// --version=v1.3.0

package app

import (
	"github.com/goadesign/goa"
)

// Article (default view)
//
// Identifier: application/vnd.article+json; view=default
type Article struct {
	// 作成者
	CreatedBy *int `form:"created_by,omitempty" json:"created_by,omitempty" xml:"created_by,omitempty"`
	// ID
	ID int `form:"id" json:"id" xml:"id"`
	// text
	Text string `form:"text" json:"text" xml:"text"`
}

// Validate validates the Article media type instance.
func (mt *Article) Validate() (err error) {

	if mt.Text == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "text"))
	}
	return
}

// ArticleCollection is the media type for an array of Article (default view)
//
// Identifier: application/vnd.article+json; type=collection; view=default
type ArticleCollection []*Article

// Validate validates the ArticleCollection media type instance.
func (mt ArticleCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}
